---
title: "Prosjekt"
author: "Martin & Chris"
date: "11/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(readr)
library(tidyr)
library(dplyr)
library(tidyverse)
library(readxl)
library(plotly)
library(lubridate)
library(tidyquant)
library(xts)
library(PerformanceAnalytics)

```

```{r}
eqnr <- read_csv("https://www.netfonds.no/quotes/paperhistory.php?paper=EQNR.OSE&csv_format=csv",
                 col_types = cols(quote_date = col_date(format = "%Y%m%d")))

eqnr_candle <- eqnr %>%
  filter(quote_date > "2016-01-01") %>%
  select(quote_date, open, close, high, low) %>%
  rename(Dato = "quote_date")


eqnr <- eqnr %>%
  select(quote_date, close) %>%
  rename(Dato = "quote_date", EQNR = "close")


eqnr_candle %>%
plotly::plot_ly(x = ~Dato, type = "ohlc",
        open = ~open, high = ~high,
        low = ~low, close = ~close) %>%
  layout(title = "Equinor 2016-")

monthly_eqnr <- eqnr %>%
  group_by(Dato=floor_date(Dato, "month")) %>%
  summarise(EQNR = mean(EQNR))

```


```{r, echo = TRUE}
osebx <- read_csv("https://www.netfonds.no/quotes/paperhistory.php?paper=OSEBX.OSE&csv_format=csv",
                       col_types = cols(quote_date = col_date(format = "%Y%m%d")))

osebx <- osebx %>%
select(quote_date, close) %>%
  rename(Dato = "quote_date", OSEBX = "close")

monthly_osebx <- osebx %>%
  group_by(Dato=floor_date(Dato, "month")) %>%
  summarise(OSEBX = mean(OSEBX))

osebx$Dato <- ymd(osebx$Dato)
```

```{r}
eiendom <- read_excel("data/eiendomnorge.no-oktober-2018-sesongjustert-oktober-2018-2018-11-05_07-32-05_738057.xlsx")

colnames(eiendom) <- c("Dato", "nominell", "korrigert")

eiendom <- eiendom %>%
  select(Dato, nominell)
```

```{r}
bitcoin <- read_csv("data/BTC_USD Bitfinex Historical Data.csv") #kan oppdateres
#glimpse(bitcoin)

bitcoin <- bitcoin %>%
  select(Date, Price) %>%
  rename(Dato = "Date", btc_usd = "Price")

bitcoin$Dato <- mdy(bitcoin$Dato)

bitcoin <- bitcoin %>% group_by(Dato=floor_date(Dato, "month")) %>%
  summarise(BTC_usd = mean(btc_usd))
```


```{r}
gull <- read_csv("data/monthly_csv.csv")                   #kanskje oppdateres?

names(gull) <- c("Dato", "Gull_usd")
gull$Dato <- parse_date_time(gull$Dato, orders = "Ym")
```

```{r}
usd_nok <- read_csv("data/USD_NOK Historical Data.csv")
usd_nok <- usd_nok %>%
  select(Date, Price) %>% 
  rename(Dato = "Date", USD_NOK = "Price")

#glimpse(usd_nok)
Sys.setlocale("LC_TIME", "C") #Slet med norske månedforkortelser i as.Date()

usd_nok$Dato <- usd_nok$Dato %>%
  as.character() %>%
  parse_date_time(.,orders = "Omy")
```

```{r echo = TRUE}
gull$Dato <- as.Date(gull$Dato)
usd_nok$Dato <- as.Date(usd_nok$Dato)
eiendom$Dato <- as.Date(eiendom$Dato)

monthly_joined <- monthly_osebx %>%
  inner_join(gull, by = "Dato") %>% 
  inner_join(usd_nok, by = "Dato") %>%
  inner_join(monthly_eqnr, by = "Dato") %>%
  inner_join(eiendom, by = "Dato")

monthly_joined

full <- osebx %>%
  full_join(gull, by = "Dato") %>% 
  full_join(usd_nok, by = "Dato") %>%
  full_join(eqnr, by = "Dato") %>%
  full_join(bitcoin, by = "Dato") %>%
  full_join(eiendom, by = "Dato")

full

```


```{r}
monthly_gathered <- monthly_joined %>%
  gather(key = "investering", value = "verdi",-Dato)

monthly_gathered <- monthly_gathered %>%
  filter(investering != "Gull_usd")

monthly_gathered$investering <- as.factor(monthly_gathered$investering)
monthly_gathered$verdi <- as.numeric(monthly_gathered$verdi)

head(monthly_gathered)
```


```{r echo = TRUE}
#monthly_returns <- monthly_gathered %>%
#  group_by(investering) %>%
#  arrange(investering, Dato) %>%
#  mutate(returns = c(NA, exp(diff(log(verdi)))-1)) %>%
#  na.omit()

tidy_monthly_returns <- monthly_gathered %>%
  group_by(investering) %>%
  tq_transmute(mutate_fun = periodReturn, period = "monthly")

total_monthly_returns <- tidy_monthly_returns %>%
  mutate(cumulative.returns = cumsum(monthly.returns))

wide_monthly_returns <- tidy_monthly_returns %>%
  spread(investering, monthly.returns)

monthly_returns_xts <- as.xts(wide_monthly_returns, order.by = wide_monthly_returns$Dato)      
monthly_returns_xts <- monthly_returns_xts[,2:5] #husk å oppdatere

sd_returns <- StdDev(monthly_returns_xts)

cumsum_test <- monthly_returns_xts %>%
  cumsum() %>%
  tail(n=1)

plot(StdDev(monthly_returns_xts), cumsum_test)
  
ggplot(total_monthly_returns, aes(x=Dato, y = cumulative.returns, color = investering))+
  geom_line()

names(monthly_returns_xts)
equal_weights = c(0.25, 0.25, 0.25, 0.25)
higher_stocks = c(0.4, 0.1, 0.4, 0.1)

#for some reason returns are class character 
storage.mode(monthly_returns_xts) <- "numeric"

StdDev(monthly_returns_xts, weights = equal_weights) # sd = 0.022
StdDev(monthly_returns_xts, weights = higher_stocks) # sd = 0.041

#Return.portfolio(monthly_returns_xts, weights = equal_weights)
sum(Return.portfolio(monthly_returns_xts, weights = equal_weights))

#Return.portfolio(monthly_returns_xts, weights = higher_stocks)
sum(Return.portfolio(monthly_returns_xts, weights = higher_stocks))
```


```{r cars}
##  Data Innhenting USA børser 

sp500 <- read_csv("data/^GSPC.csv", col_types = cols(Date = col_date(format = "%Y-%m-%d")))

colnames(sp500) <-   c("Dato", "Open", "High", "Low", "Close",  "Adj.Close", "Volume")

#colnames(sp500)

nasdaq <- read_csv("data/NASDAQ.Composite.1970-2018.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))

colnames(nasdaq) <- c("Dato", "Open", "High", "Low", "Close",  "Adj.Close", "Volume")

#colnames(nasdaq)

dowj <- read_csv("data/Dow Jones Industrial Average 1970-2018.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))

colnames(dowj) <- c("Dato", "Open", "High", "Low", "Close",  "Adj.Close", "Volume")

#colnames(dowj)


ggplot() + 
geom_line(data=nasdaq, aes(x=Dato, y=Adj.Close), color='green')+ 
geom_line(data=sp500, aes(x=Dato, y=Adj.Close), color='red')+
geom_line(data=dowj, aes(x=Dato, y=Adj.Close), color='blue') 



```



```{r pressure}

### Eiendom priser 
#oecd.hus <- read_csv("DP_LIVE_27112018111628959.csv")
#oecd.hus <- filter(oecd.hus, SUBJECT == "NOMINAL")
#oecd.hus <- filter(oecd.hus, FREQUENCY == "Q")
#oecd.hus$TIME <- str_replace(oecd.hus$TIME, "Q1", "01-01") 
#oecd.hus$TIME <- str_replace(oecd.hus$TIME, "Q2", "01-04") 
#oecd.hus$TIME <- str_replace(oecd.hus$TIME, "Q3", "01-07") 
#oecd.hus$TIME <- str_replace(oecd.hus$TIME, "Q4", "01-10") 
#oecd.hus$TIME <- as.Date(oecd.hus$TIME, "%Y-%m-%d")
#colnames(oecd.hus[6]) <- "Dato"
#colnames(oecd.hus)

#ggplot(oecd.hus) +
#geom_line(aes(x=TIME, y= Value)) 

# Data sett med månedlig eiendom data 

eiendom <- read_excel("data/eiendomnorge.no-oktober-2018-sesongjustert-oktober-2018-2018-11-05_07-32-05_738057.xlsx")

colnames(eiendom) <- c("Dato", "nominell", "korrigert")


ggplot(eiendom) +
geom_line(aes(x=Dato, y=nominell))  


```


```{r}

# Norges Bank - styringsrente


renter <- read_excel("data/renter_mnd.xlsx",
    col_types = c("date", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text"))

renter[3:13] <- NULL 

renter <- na.omit(renter)

colnames(renter) <- c("Dato", "styringsrente")

colnames(renter)


plot(renter$Dato, renter$styringsrente, type = "l")


# FED - USA renter 

usa.rente <- read_csv("data/FEDFUNDS.csv")

colnames(usa.rente) <- c("Dato", "styringsrente.usa")

# colnames(usa.rente)

#str(usa.rente)



```



```{r}

#DOWogSP <- bind_cols(dowj$Adj.Close, sp500$Adj.Close, by= "Dato")

### styringsrenten ville ikke plottes, muligens pga andre antallobservasjoner

#ggplot() + 
#geom_line(data=nasdaq, aes(x=Dato, y=Adj.Close), color='green')+ 
#geom_line(data=sp500, aes(x=Dato, y=Adj.Close), color='red')+
#geom_line(data=dowj, aes(x=Dato, y=Adj.Close), color='blue') 
#geom_line(data=usa.rente, aes(x=Dato, y=styringsretna.usa), color='organge') 



```

